In [22]:
# pip install yfinance

In [23]:
import pandas as pd
import yfinance as yf

In [24]:
sp500url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
data_table = pd.read_html(sp500url)

In [25]:
data_table

[    Symbol             Security             GICS Sector  \
 0      MMM                   3M             Industrials
 1      AOS          A. O. Smith             Industrials
 2      ABT  Abbott Laboratories             Health Care
 3     ABBV               AbbVie             Health Care
 4      ACN            Accenture  Information Technology
 ..     ...                  ...                     ...
 498    XYL           Xylem Inc.             Industrials
 499    YUM          Yum! Brands  Consumer Discretionary
 500   ZBRA   Zebra Technologies  Information Technology
 501    ZBH        Zimmer Biomet             Health Care
 502    ZTS               Zoetis             Health Care

                                 GICS Sub-Industry    Headquarters Location  \
 0                        Industrial Conglomerates    Saint Paul, Minnesota
 1                               Building Products     Milwaukee, Wisconsin
 2                           Health Care Equipment  North Chicago, Illinois
 3                                   Biotechnology  North Chicago, Illinois
 4                  IT Consulting & Other Services          Dublin, Ireland
 ..                                            ...                      ...
 498  Industrial Machinery & Supplies & Components   White Plains, New York
 499                                   Restaurants     Louisville, Kentucky
 500            Electronic Equipment & Instruments   Lincolnshire, Illinois
 501                         Health Care Equipment          Warsaw, Indiana
 502                               Pharmaceuticals   Parsippany, New Jersey

      Date added      CIK      Founded
 0    1957-03-04    66740         1902
 1    2017-07-26    91142         1916
 2    1957-03-04     1800         1888
 3    2012-12-31  1551152  2013 (1888)
 4    2011-07-06  1467373         1989
 ..          ...      ...          ...
 498  2011-11-01  1524472         2011
 499  1997-10-06  1041061         1997
 500  2019-12-23   877212         1969
 501  2001-08-07  1136869         1927
 502  2013-06-21  1555280         1952

 [503 rows x 8 columns],
                   Date  Added                                Removed  \
                   Date Ticker                       Security  Ticker
 0       March 24, 2025   DASH                       DoorDash     BWA
 1       March 24, 2025    TKO             TKO Group Holdings     TFX
 2       March 24, 2025    WSM          Williams-Sonoma, Inc.      CE
 3       March 24, 2025    EXE                  Expand Energy     FMC
 4    December 23, 2024    APO       Apollo Global Management    QRVO
 ..                 ...    ...                            ...     ...
 366  December 11, 1998   CPWR                      Compuware     SUN
 367      June 17, 1997    CCI  Countrywide Credit Industries     USL
 368       Sep 30, 1994    NCC                  National City     MCK
 369        Jul 1, 1976    BUD                 Anheuser Busch     HNG
 370        Jul 1, 1976    DIS        The Walt Disney Company     AYE

                                                                      Reason
                 Security                                             Reason
 0             BorgWarner                   Market capitalization change.[4]
 1               Teleflex                   Market capitalization change.[4]
 2               Celanese                   Market capitalization change.[4]
 3        FMC Corporation                   Market capitalization change.[4]
 4                  Qorvo                   Market capitalization change.[5]
 ..                   ...                                                ...
 366           SunAmerica                     AIG purchased SunAmerica.[262]
 367               USLife                          AIG acquired USLife.[263]
 368             McKesson  McKesson sold PCS Health Services to Eli Lilly...
 369  Houston Natural Gas  Major restructuring of S&P 500 to have fewer i...
 370     Allegheny Energy  Major restructuring of S&P 500 to have fewer i...

 [371 rows x 6 columns]]

In [26]:
len(data_table)

2

In [27]:
data_table[0]

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [28]:
tickers = data_table[0]['Symbol'].tolist()
tickers = [ticker.replace('.', '-') for ticker in tickers]

In [29]:
tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK-B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BK',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF-B',
 'BLDR',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [30]:
len(tickers)

503

In [39]:
snp_prices = yf.download(tickers, start='2024-04-01', end='2025-04-01')['Close']

[*********************100%***********************]  503 of 503 completed

In [40]:
snp_prices

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2024-04-01,144.484848,169.230911,174.406769,163.369995,109.851318,87.777443,335.022888,502.089996,193.409790,60.075546,...,270.207550,34.629753,105.362244,51.430157,113.170059,127.212418,137.767349,128.609497,301.000000,165.257538
2024-04-02,143.105087,168.046509,174.339249,160.110001,109.782722,86.997704,332.346008,499.209991,191.698212,60.412781,...,264.644043,34.503147,104.076866,52.202385,115.385292,126.698181,138.002716,127.340759,296.500000,163.268738
2024-04-03,142.668350,168.852707,171.097336,159.339996,109.057503,87.701378,328.217133,497.010010,192.170380,60.364609,...,266.116425,34.025967,105.223831,52.212036,115.404640,127.429985,136.335449,128.867218,292.750000,161.250275
2024-04-04,140.296005,168.026611,161.998764,158.839996,107.910873,86.617340,326.429260,487.109985,188.816025,60.933086,...,263.171692,33.733814,104.927193,51.903145,115.810928,125.837837,133.657959,126.438759,292.959991,163.773376
2024-04-05,143.055466,168.783035,164.024963,161.770004,108.979095,90.240273,328.928314,485.119995,191.580154,61.145058,...,267.737061,33.685127,106.252129,51.671478,117.407051,126.846527,133.481415,126.210785,290.380005,164.109772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-25,120.254517,223.750000,201.339996,129.880005,125.599998,94.580002,308.899994,403.640015,213.580002,46.049999,...,337.007874,29.200001,86.029999,67.930000,116.589996,123.089996,155.800003,110.144012,291.019989,161.300003
2025-03-26,119.645813,221.529999,201.300003,128.639999,126.610001,95.930000,311.160004,397.809998,210.529999,47.070000,...,337.666077,29.420000,85.830002,68.919998,118.269997,123.129997,158.679993,110.403465,288.019989,162.820007
2025-03-27,118.717781,223.850006,202.720001,125.650002,131.350006,96.940002,308.529999,396.149994,208.940002,48.279999,...,339.949860,29.590000,86.150002,69.320000,117.889999,122.019997,157.649994,111.910233,285.140015,165.020004
2025-03-28,116.442619,217.899994,205.289993,120.690002,130.820007,95.059998,304.329987,385.709991,201.559998,47.869999,...,336.239990,29.360001,82.330002,69.720001,117.730003,119.440002,155.759995,112.020004,280.790009,163.110001
2025-03-31,116.732002,222.130005,209.520004,119.459999,132.649994,96.180000,312.040009,383.529999,201.669998,48.009998,...,337.950012,29.280001,83.500000,70.790001,118.930000,119.459999,157.360001,113.180000,282.559998,164.649994

In [41]:
snp_prices.isna().any()

Ticker
A       False
AAPL    False
ABBV    False
ABNB    False
ABT     False
        ...
XYL     False
YUM     False
ZBH     False
ZBRA    False
ZTS     False
Length: 503, dtype: bool

In [42]:
snp_prices.loc[:, snp_prices.isna().any()]

Ticker             SW
Date
2024-04-01        NaN
2024-04-02        NaN
2024-04-03        NaN
2024-04-04        NaN
2024-04-05        NaN
...               ...
2025-03-25  45.570000
2025-03-26  45.279999
2025-03-27  45.400002
2025-03-28  44.509998
2025-03-31  45.060001

[251 rows x 1 columns]

In [43]:
# Xử lý dữ liệu thiếu
snp_prices.bfill(inplace=True)

In [44]:
len(snp_prices.columns)

503

In [45]:
snp_prices

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2024-04-01,144.484848,169.230911,174.406769,163.369995,109.851318,87.777443,335.022888,502.089996,193.409790,60.075546,...,270.207550,34.629753,105.362244,51.430157,113.170059,127.212418,137.767349,128.609497,301.000000,165.257538
2024-04-02,143.105087,168.046509,174.339249,160.110001,109.782722,86.997704,332.346008,499.209991,191.698212,60.412781,...,264.644043,34.503147,104.076866,52.202385,115.385292,126.698181,138.002716,127.340759,296.500000,163.268738
2024-04-03,142.668350,168.852707,171.097336,159.339996,109.057503,87.701378,328.217133,497.010010,192.170380,60.364609,...,266.116425,34.025967,105.223831,52.212036,115.404640,127.429985,136.335449,128.867218,292.750000,161.250275
2024-04-04,140.296005,168.026611,161.998764,158.839996,107.910873,86.617340,326.429260,487.109985,188.816025,60.933086,...,263.171692,33.733814,104.927193,51.903145,115.810928,125.837837,133.657959,126.438759,292.959991,163.773376
2024-04-05,143.055466,168.783035,164.024963,161.770004,108.979095,90.240273,328.928314,485.119995,191.580154,61.145058,...,267.737061,33.685127,106.252129,51.671478,117.407051,126.846527,133.481415,126.210785,290.380005,164.109772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-25,120.254517,223.750000,201.339996,129.880005,125.599998,94.580002,308.899994,403.640015,213.580002,46.049999,...,337.007874,29.200001,86.029999,67.930000,116.589996,123.089996,155.800003,110.144012,291.019989,161.300003
2025-03-26,119.645813,221.529999,201.300003,128.639999,126.610001,95.930000,311.160004,397.809998,210.529999,47.070000,...,337.666077,29.420000,85.830002,68.919998,118.269997,123.129997,158.679993,110.403465,288.019989,162.820007
2025-03-27,118.717781,223.850006,202.720001,125.650002,131.350006,96.940002,308.529999,396.149994,208.940002,48.279999,...,339.949860,29.590000,86.150002,69.320000,117.889999,122.019997,157.649994,111.910233,285.140015,165.020004
2025-03-28,116.442619,217.899994,205.289993,120.690002,130.820007,95.059998,304.329987,385.709991,201.559998,47.869999,...,336.239990,29.360001,82.330002,69.720001,117.730003,119.440002,155.759995,112.020004,280.790009,163.110001
2025-03-31,116.732002,222.130005,209.520004,119.459999,132.649994,96.180000,312.040009,383.529999,201.669998,48.009998,...,337.950012,29.280001,83.500000,70.790001,118.930000,119.459999,157.360001,113.180000,282.559998,164.649994

In [47]:
# Xuất dữ liệu ra tệp CSV
snp_prices.to_csv('snp_prices.csv', index=True)